# Light image for producer
FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir kafka-python
COPY kafka/producer.py .
# Leave running to call using docker exec
CMD ["python", "producer.py"]
